name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node14.16.0-chrome88-ff70
    steps:
      - name: Cypress run
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          spec: cypress/integration/tickets.spec.js
          record: true
          tag: node-${{ matrix.node }}